//! Body building blocks for the contract.
//!
//! Two types live here:
//!
//! - [`BoxBody`] — type-erased body for cold paths (admin endpoints,
//!   error responses, the lifecycle's "different ingress and egress
//!   body type" forwarding case). Boxing happens at most once per
//!   request, on construction.
//! - [`VecBody`] — deterministic in-memory body used by contract tests
//!   and by callers that already have the full payload in memory
//!   (synthetic admin responses, error pages, etc.).

use std::collections::VecDeque;
use std::convert::Infallible;
use std::pin::Pin;
use std::task::{Context, Poll};

use bytes::Bytes;
use http_body::{Body, Frame, SizeHint};
use http_body_util::BodyExt;

/// Type-erased body alias. Wraps any `B: Body<Data = Bytes>` whose
/// error type can be converted into a boxed error.
///
/// Only used on **cold paths**. The hot per-request flow stays generic
/// over `B` to avoid the per-request box allocation.
pub type BoxBody =
    http_body_util::combinators::BoxBody<Bytes, Box<dyn std::error::Error + Send + Sync + 'static>>;

/// Wrap any compatible body in a [`BoxBody`]. Convenience for the cold
/// paths that need to erase concrete body types.
pub fn boxed<B>(body: B) -> BoxBody
where
    B: Body<Data = Bytes> + Send + Sync + 'static,
    B::Error: Into<Box<dyn std::error::Error + Send + Sync + 'static>>,
{
    body.map_err(Into::into).boxed()
}

/// Deterministic in-memory body: yields each pre-loaded chunk once,
/// then optional trailers, then ends.
///
/// Use cases:
/// - Contract tests in this crate (and downstream).
/// - Synthetic responses generated by the lifecycle layer (error
///   pages, admin JSON). These are cold-path consumers; the per-frame
///   `pop_front` cost is negligible compared to the alternative of
///   building a one-off body type per call site.
#[derive(Debug, Default)]
pub struct VecBody {
    chunks: VecDeque<Bytes>,
    trailers: Option<http::HeaderMap>,
}

impl VecBody {
    /// An empty body.
    pub fn empty() -> Self {
        Self::default()
    }

    /// Build from chunks, no trailers.
    pub fn from_chunks(chunks: impl IntoIterator<Item = Bytes>) -> Self {
        Self {
            chunks: chunks.into_iter().collect(),
            trailers: None,
        }
    }

    /// Build from one contiguous payload, no trailers.
    pub fn from_bytes(bytes: Bytes) -> Self {
        if bytes.is_empty() {
            Self::empty()
        } else {
            Self {
                chunks: VecDeque::from([bytes]),
                trailers: None,
            }
        }
    }

    /// Replace the trailers.
    pub fn with_trailers(mut self, trailers: http::HeaderMap) -> Self {
        self.trailers = Some(trailers);
        self
    }

    /// Total bytes still buffered (sum across remaining chunks). Used
    /// by the contract tests; not on any hot path.
    pub fn remaining(&self) -> usize {
        self.chunks.iter().map(bytes::Bytes::len).sum()
    }
}

impl Body for VecBody {
    type Data = Bytes;
    type Error = Infallible;

    fn poll_frame(
        self: Pin<&mut Self>,
        _cx: &mut Context<'_>,
    ) -> Poll<Option<Result<Frame<Bytes>, Self::Error>>> {
        let me = self.get_mut();
        if let Some(chunk) = me.chunks.pop_front() {
            return Poll::Ready(Some(Ok(Frame::data(chunk))));
        }
        if let Some(trailers) = me.trailers.take() {
            return Poll::Ready(Some(Ok(Frame::trailers(trailers))));
        }
        Poll::Ready(None)
    }

    fn is_end_stream(&self) -> bool {
        self.chunks.is_empty() && self.trailers.is_none()
    }

    fn size_hint(&self) -> SizeHint {
        let bytes = self.remaining() as u64;
        SizeHint::with_exact(bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::future::Future;
    use std::sync::Arc;
    use std::task::{Wake, Waker};

    /// Std-only `block_on` for futures that never return `Pending`.
    /// Sufficient for [`VecBody`] (always immediately ready) and for
    /// `BodyExt::collect` over an `Infallible` body.
    fn block_on<F: Future>(fut: F) -> F::Output {
        struct Nop;
        impl Wake for Nop {
            fn wake(self: Arc<Self>) {}
        }
        let waker = Waker::from(Arc::new(Nop));
        let mut cx = Context::from_waker(&waker);
        let mut fut = std::pin::pin!(fut);
        loop {
            if let Poll::Ready(v) = fut.as_mut().poll(&mut cx) {
                return v;
            }
            // No yield strategy: VecBody never returns Pending. If a
            // future passed here did, we'd spin — that's a test bug.
        }
    }

    #[test]
    fn empty_body_yields_none_and_is_end_stream() {
        let mut b = VecBody::empty();
        let nop = Waker::from(Arc::new({
            struct Nop;
            impl Wake for Nop {
                fn wake(self: Arc<Self>) {}
            }
            Nop
        }));
        let mut cx = Context::from_waker(&nop);
        match Pin::new(&mut b).poll_frame(&mut cx) {
            Poll::Ready(None) => {}
            other => panic!("expected Ready(None), got {other:?}"),
        }
        assert!(b.is_end_stream());
        assert_eq!(b.size_hint().exact(), Some(0));
    }

    #[test]
    fn chunks_yield_in_order() {
        let chunks = vec![Bytes::from_static(b"foo"), Bytes::from_static(b"bar")];
        let b = VecBody::from_chunks(chunks);
        let collected = block_on(b.collect()).expect("Infallible");
        assert_eq!(&collected.to_bytes()[..], b"foobar");
    }

    #[test]
    fn trailers_arrive_after_data() {
        let mut h = http::HeaderMap::new();
        h.insert("x-trailer", http::HeaderValue::from_static("end"));
        let b = VecBody::from_bytes(Bytes::from_static(b"payload")).with_trailers(h.clone());
        assert!(!b.is_end_stream());

        let collected = block_on(b.collect()).expect("Infallible");
        let trailers = collected.trailers().cloned();
        assert_eq!(trailers.as_ref(), Some(&h));
        assert_eq!(&collected.to_bytes()[..], b"payload");
    }

    #[test]
    fn size_hint_exact_matches_remaining() {
        let b = VecBody::from_chunks([Bytes::from_static(b"abc"), Bytes::from_static(b"defg")]);
        assert_eq!(b.size_hint().exact(), Some(7));
    }

    #[test]
    fn from_empty_bytes_is_empty() {
        let b = VecBody::from_bytes(Bytes::new());
        assert!(b.is_end_stream());
        assert_eq!(b.size_hint().exact(), Some(0));
    }

    #[test]
    fn boxed_round_trips() {
        let b = VecBody::from_bytes(Bytes::from_static(b"abc"));
        let boxed = crate::body::boxed(b);
        let collected = block_on(boxed.collect()).expect("error");
        assert_eq!(&collected.to_bytes()[..], b"abc");
    }
}
